#version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: sio-postgres
    environment:
      POSTGRES_USER: sio_user
      POSTGRES_PASSWORD: sio_password
      POSTGRES_DB: sio_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: sio-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: sio_user
      DB_PASS: sio_password
      DB_NAME: sio_db
      JWT_SECRET: "chiave_segreta_super_sicura_per_il_corso_segretissimissima"
      AUTH_ENABLED: "false"
    depends_on:
      - db
    restart: always

  # AMBIENTE PROD (BLUE)
  frontend-prod:
    build:
      context: ./his-afp
      dockerfile: Dockerfile
    image: his-afp:${PROD_VERSION:-stable}
    container_name: sio-frontend-prod
    environment:
      APP_ENV: "prod"

  # AMBIENTE TEST (GREEN)
  frontend-test:
    build:
      context: ./his-afp
      dockerfile: Dockerfile
    image: his-afp:${TEST_VERSION:-latest}
    container_name: sio-frontend-test
    environment:
      APP_ENV: "test"

  # AMBIENTE TEST (GREEN)
  frontend-formazione:
    build:
      context: ./his-afp
      dockerfile: Dockerfile
    image: his-afp:${TRAINING_VERSION:-latest}
    container_name: sio-frontend-formazione
    environment:
      APP_ENV: "form"

  # GATEWAY
  gateway:
    image: nginx:alpine
    container_name: sio-gateway
    ports:
      - "80:80"       # Produzione
      - "8080:8080"   # Test
      - "8888:8888"   # Formazione
    volumes:
      - ./gateway:/etc/nginx/conf.d/:ro
    depends_on:
      - frontend-prod
      - frontend-test
      - frontend-formazione
    restart: always

volumes:
  pg_data:
