#version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: sio-postgres
    environment:
      POSTGRES_USER: sio_user
      POSTGRES_PASSWORD: sio_password
      POSTGRES_DB: sio_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: sio-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: sio_user
      DB_PASS: sio_password
      DB_NAME: sio_db
      JWT_SECRET: "chiave_segreta_super_sicura_per_il_corso_segretissimissima"
      AUTH_ENABLED: "false"
    depends_on:
      - db
    restart: always

  # FE BLUE (STABILE)
  frontend-blue:
    build:
      context: ./his-afp
      dockerfile: Dockerfile
    container_name: sio-frontend-blue
    environment:
      APP_ENV: "prod"

  # FE GREEN (IN SVILUPPO)
  frontend-green:
    build:
      context: ./his-afp
      dockerfile: Dockerfile
    container_name: sio-frontend-green
    environment:
      APP_ENV: "test"

  # GATEWAY
  gateway:
    image: nginx:alpine
    container_name: sio-gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend-blue
      - frontend-green
    restart: always

volumes:
  pg_data:
