# stream {
#     upstream sio-db {
#         server sio-db:5432;
#     }
#     server {
#         proxy_pass sio-db;
#     }
# }

# CONNESSIONE DB POSTGRESS
server{
    listen 5432 so_keepalive=on;

    location / {
        proxy_pass sio-db:5432;
    }
}

# AMBIENTE PROD
server{
    listen 80;
    location / {
        proxy_pass http://fe-prod:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sio-backend:3000;
    }
}

# AMBIENTE TEST
server{
    listen 8080;
    location / {
        proxy_pass http://fe-test:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sio-backend:3000;
    }
}

# AMBIENTE SVI
server{
    listen 8999;
    location / {
        proxy_pass http://fe-sio:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sio-backend:3000;
    }
}

