server {
    listen 80;
    server_name localhost;
    location / { proxy_pass http://frontend-prod:80; }
    location /api/ { proxy_pass http://sio-backend:3000/; }
}

server {
    listen 8080;
    location / { proxy_pass http://frontend-test:80; }
    location /api/ { proxy_pass http://sio-backend:3000/; }
}

server {
    listen 8888;
    location / { proxy_pass http://frontend-formazione:80; }
    location /api/ { proxy_pass http://sio-backend:3000/; }
}
