server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # Rimuoviamo la parte /api/ da qui, perché se ne occupa il Gateway
}
